# =================================================================
# 找箱器：说明
# chunk_distance: 最大区块查找距离。越大越卡，若查找未加载区块会报错，建议不超过2。
# chest_effect: 提示特效类型，取值为整数。
# chunk_chest_limit: 每个区块遍历的箱子上限数目。
# 1 - 隐形发光潜影贝特效（默认），0 - 粒子特效
# 没有ProtocolLib时自动使用粒子特效；如果提示显示不正常或报错，也请改为粒子特效。
# =================================================================
chunk_distance: 1
chest_effect: 1
chunk_chest_limit: 128
