# =================================================================
# 物品收集站：说明
# distance: 收集最大半径（收集范围过大会导致卡服，且易使玩家窃取他人领地掉落物，建议设置在16以内）
# classify_name: 将物品用铁砧命名为这个名字，放在箱子第一格，收集站将只往箱子中放入该类物品。建议用特殊符号开头以兼容箱子整理插件。
# max_amount_per_chunk: 每区块的最大收集器数量。降低卡服可能性。
# over_chunk_limit_tips: 收集器数量超出区块上限的提示。
# full_chest_effect: 满箱提示特效类型，取值为整数。
# 0 - 不启用特效，1 - 隐形发光潜影贝特效（默认），2 - 发光冰块特效，3 - 粒子特效
# 没有ProtocolLib时自动使用粒子特效；如果满箱提示显示不正常或报错，也请改为粒子特效。
# collector：收集站盔甲架。可酌情自行修改说明
# =================================================================
distance: 10
max_amount_per_chunk: 4
classify_name: '#分类'
over_chunk_limit_tips: §c本区块收集器大于%d个，无法放置!
full_chest_effect: 1
